tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"

brew "ack"
brew "ant"
brew "chromedriver"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "fish"
brew "go"
brew "sqlite"
brew "python3"
brew "grc"
brew "groovy"
brew "heroku"
brew "imagemagick"
brew "iperf3"
brew "jmeter"
brew "lua"
brew "mackup"
brew "python"
brew "macvim", args: ["with-override-system-vim"]
brew "maven"
brew "neovim"
brew "phantomjs"
brew "pkg-config"
brew "qt"
brew "redis", restart_service: true
brew "roundup"
brew "rust"
brew "the_silver_searcher"
brew "unrar"
brew "watchman"
brew "wget"
brew "zsh-syntax-highlighting"

cask "java"
cask "1password"
cask "cargo"
cask "transmission"
