publish:
    image: aem_publish:6.3
    mem_limit: 2g
    ports:
        - "4503:4503"

author:
    image: aem_author:6.3
    mem_limit: 2g
    ports:
        - "4502:4502"
    links:
        - publish

# dispatcher:
#     image: aem_dispatcher:6.3
#     ports:
#         - "80:80"
#     links:
#         - publish
