#!/usr/bin/env fish



# Run install files for all files named 'install.sh'
for file in (find -H $DOTS -maxdepth 2 -name "install.*sh")
  # sh -c $file
  echo "About to install: $file"
  # TODO: Handle both .fish and .sh files
end
