#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTS=$(pwd -P)

# Install homebrew
echo "> Installing Homebrew..."
$DOTS/homebrew/install.sh 2>&1

# Install brews from Brewfile at $DOTS
echo "> Brewing from Brewfile"
cd $DOTS && brew bundle

# Install fish with homebrew
brew install fish
# May need to add /usr/local/bin/fish to /etc/shells and then use:
# `chsh -s /usr/local/bin/fish`

# continue with fish in different file
$DOTS/script/fish_install
