#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

# Install homebrew
$DOTFILES_ROOT/homebrew/install.sh 2>&1

# Install brews from Brewfile at $DOTFILES_ROOT
cd $DOTFILES_ROOT && brew bundle

# Install brews from Brewfile

# Install fish with homebrew
# brew install fish
# May need to add /usr/local/bin/fish to /etc/shells and then use:
# `chsh -s /usr/local/bin/fish`

# continue with fish in different file
$DOTFILES_ROOT/script/fish_install
